### ISSUE TITLE
wordart database issue

### ISSUE THREAD

**Issue by henrymzhao** [henrymzhao/csss-minion#67]
```[3:14 PM] BOTDoraemon: Ignoring exception in message
[3:14 PM] BOTDoraemon: Traceback (most recent call last):
[3:14 PM] BOTDoraemon: File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 252, in _run_extra
[3:14 PM] BOTDoraemon: yield from coro(*args, **kwargs)
[3:14 PM] BOTDoraemon: File "/home/henry/csss-minion/wordart.py", line 171, in on_message
[3:14 PM] BOTDoraemon: cur.execute(query, data)
[3:14 PM] BOTDoraemon: psycopg2.IntegrityError: duplicate key value violates unique constraint "wordartmessages_user_id_date_key"
[3:14 PM] BOTDoraemon: DETAIL:  Key (user_id, date)=(293110345076047893, 2017-10-09 22:14:19.901) already exists.```

**Comment by henrymzhao** [comment]
#68
